### PR TITLE
adds basic versions of pivot_longer and pivot_wider

### PR DESCRIPTION
**Pull request by rdboyes**
adds pivot_longer with support for one argument (cols) and pivot_wider with support for (names_from, values_from). Also cleans up runtests.jl to allow doctests to easily be run locally using `] test`

### CODE REVIEW

**Comment by rdboyes** [comment]
Not sure how much of the functionality of `pivot_longer` and `pivot_wider` is needed before they're useful - wanted to check in on the general approach before implementing too many options. In particular, is this how you want to handle processing arguments? Or was there another way already implemented that I didn't catch

**Comment by kdpsingh** [comment]
The only other addition will be to add a page to the documentation page dedicated to pivoting. You're welcome to do it, but others can also help if you'd like.

**Comment by rdboyes** [comment]
Renaming done - I might wait on a full documentation page just because a lot of the more practical examples (e.g. something resembling https://tidyr.tidyverse.org/articles/pivot.html) will require additional options to be implemented first

**Comment by kdpsingh** [comment]
Perfect. I'll put together a basic docs page and then plan to get this merged tonight.

**Comment by kdpsingh** [comment]
Yeah, as a next step we can implement `names_to` and `values_to`. I don't think we necessarily need to implement all the bells and whistles, and certainly not yet.

**Pull request merged**
